#!/bin/bash
path=cpp/compile
mkdir $path
cd $path
cmake ..
make
examples=../../examples/
for f in {0..9}
do
    in="${examples}in${f}"
    out="${examples}out${f}"
    ./cpp $f $in $out
done
cd ../../
rm -rf $path
